[package]
name = "currency-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "currency-converter"
path = "src/main.rs"

[lib]
name = "currency"
path = "src/currency/lib.rs"

[dependencies]
maplit = "1.0.2"
clap = { version = "4.5.2", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
async-trait = "0.1.78"
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
reqwest = "0.11.26"
mockall = { version = "0.12.1" }
