[package]
name = "currency-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "currency-converter"
path = "src/main.rs"

[lib]
name = "currency"
path = "src/currency/lib.rs"

[dependencies]
async-trait = "0.1.78"
