[package]
name = "currency-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
async-trait = "0.1.80"
serde_json = "1.0.117"
derive_more = "0.99.18"

[dev-dependencies]
serde_test = "1.0"
